### ISSUE TITLE
Any plan for locazilation?

### ISSUE THREAD

**Issue by EKE00372** [Elitesparkle/Animosity#1]
Do you have any plan for locazilation? if you interested, I can support zhTW/zhCN.

**Comment by Elitesparkle** [comment]
It wasn't planned but I can implement it. Please, translate strings [here](https://legacy.curseforge.com/wow/addons/animosity/localization).

**Comment by EKE00372** [comment]
both done.

just notice i can pr directly......

**Comment by Elitesparkle** [comment]
Thanks! The translation will be released in a couple of hours.

Don't worry, I'm happy to help by implementing new features.

**Comment by EKE00372** [comment]
Just do a change on proc glow translate, may need one more update.

I use description instead translate one by one word, longer but better to understand O.o

for example zhTW translate `active` as 啟動 before, but druid's `Innervate` named 啟動 too.

**Comment by Elitesparkle** [comment]
Ok, that's fine.
